development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:1f92e82bf0794e2fbd36c886809249ee@spinyfin.redistogo.com:9836/
  channel_prefix: fts_81_production
