---
development:
  cloud_name: tuan-anh-uet-vnu
  api_key: '352976763721713'
  api_secret: xy5vlARqxh8A0jdAwATIKPUSG3g
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: tuan-anh-uet-vnu
  api_key: '352976763721713'
  api_secret: xy5vlARqxh8A0jdAwATIKPUSG3g
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: tuan-anh-uet-vnu
  api_key: '352976763721713'
  api_secret: xy5vlARqxh8A0jdAwATIKPUSG3g
  enhance_image_tag: true
  static_file_support: false
