image_size: 2
regex:
  phone: !ruby/regexp /\A[0]\d{1}[0-9]*$\b/i
  user_password: !ruby/regexp /\s/
user:
  per_page_index: 10
  per_page: 6
  user_name:
    max_length: 125
    min_length: 3
  phone:
    max_length: 25
    min_length: 1
  email:
    max_length: 125
    min_length: 8
  address:
    max_length: 256
    min_length: 1
comment:
  rows: 4
per_page: 6
per_page_index: 5
course:
  per_page: 5
pages:
  per: 10
course_times: 2
task_times: 2
avatar_trainee: "https://res.cloudinary.com/tuan-anh-uet-vnu/image/asset/v1550286380/trainee-53980210f1499309f1169161d38fe78e.png"
avatar_teacher: "https://res.cloudinary.com/tuan-anh-uet-vnu/image/asset/v1550286377/teacher-491ef244e7cc377cacd2d4d1a2bc552d.png"
image_course: "https://res.cloudinary.com/tuan-anh-uet-vnu/image/asset/v1550286368/course-26ff8f39241b3a8a90817f04f86d2214.png"
format_time: "%d/%m/%Y"
format_time_test: "%H:%M %d/%m/%Y"
