regex:
  phone: !ruby/regexp /\A[0]\d{1}[0-9]*$\b/i
  user_password: !ruby/regexp /\s/
user:
  per_page_index: 10
  per_page: 6
  user_name:
    max_length: 125
    min_length: 3
  phone:
    max_length: 25
    min_length: 1
  email:
    max_length: 125
    min_length: 2
  address:
    max_length: 256
    min_length: 1
comment:
  rows: 2
  max_length: 1256
  min_length: 1
per_page: 10
course:
  per_page: 5
pages:
  per: 10
course_times: 2
task_times: 2
default_image: "/assets/training.png"
format_time: "%d/%m/%Y"
mail_from: "tuananhk60uet@gmail.com"
